### ISSUE TITLE
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@357ccd6b(incomplete)

### ISSUE THREAD

**Issue by dragontree101** [jurmous/etcd4j#112]
how does will have this exception

```
io.netty.util.concurrent.BlockingOperationException: DefaultPromise@357ccd6b(incomplete)
at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:391)
at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:284)
at mousio.client.promises.ResponsePromise.waitForPromiseSuccess(ResponsePromise.java:189)
at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:58)
....
```

and this exception code is 

```
EtcdKeysResponse response = etcdClient.get(listenPath).send().get();
```

i found some times will throw this exception, but some times throw this exception

why will throw this exception? and how can i solve this exception?

**Comment by asdfghhong** [comment]
we also meet this error, how to fix it

**Comment by jcai** [comment]
How to fix it ?
