### ISSUE TITLE
etcd4j doesn't work in servlet server

### ISSUE THREAD

**Issue by armstrongli** [jurmous/etcd4j#125]
In tomcat or jetty server, it doesn't work with SSL enabled etcd server.
It throws out exception:
```
java.lang.IllegalStateException: Load library failed!
       	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:261)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:250)
       	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:242)
       	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:194)
       	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:166)
       	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:380)
       	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:99)
       	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:206)
       	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:198)
       	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
       	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:187)
       	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:753)
       	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:397)
Caused by: java.lang.reflect.InvocationTargetException
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:497)
       	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:259)
       	... 16 more
Caused by: java.lang.UnsatisfiedLinkError: no netty-tcnative-osx-x86_64 in java.library.path
       	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
       	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
       	at java.lang.System.loadLibrary(System.java:1122)
       	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
       	... 21 more
```

**Comment by lburgazzoli** [comment]
Looks like a netty issue can you digg it a little bit more and tell us if we have something to change to make it working or have a better support ?

**Comment by armstrongli** [comment]
It doesn't work in alpine linux base java servlet server.

**Comment by armstrongli** [comment]
Logs show that the error comes out while loading the `so` file.

**Comment by lburgazzoli** [comment]
There are a number of related issues about netty-tcnative on alpine-linux, should be discussed on netty ml

**Comment by armstrongli** [comment]
Here are some details of output:
```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative3270913869898400045.so: Error relocating /tmp/libnetty-tcnative3270913869898400045.so: SSL_add0_chain_cert: symbol not found
       	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
       	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
       	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
       	at java.lang.Runtime.load0(Runtime.java:809)
       	at java.lang.System.load(System.java:1086)
       	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
       	... 21 more
```

If the image base is ubuntu, there won't be any error.

**Comment by lburgazzoli** [comment]
I believe you need a specific libnetty-tcnative as most of the stuffs in alpine linux are statically linked
