### ISSUE TITLE
1 node etcd cluster is not working

### ISSUE THREAD

**Issue by suresh-chaudhari** [jurmous/etcd4j#144]
To work etcd client , I find that it requires minimum 2 etcd node up to store any data in etcd server. 

Issue:
I have created the cluster of 3 etcd node and down 2 etcd node , If we down 2 etcd node it is not able to call the etcd server.

Please resolve this issue ASAP for etcd cluster.

**Comment by lburgazzoli** [comment]
Can you provide some more details ?

- how to reproduce it 
- the version you are using (both etcd ad etcd4j)
- how the etcd cluster is set up
- etcd

**Comment by suresh-chaudhari** [comment]
Hi. 

Find the all details below:
etcd-server version: 3.1.5
org.mousio etcd4j client version: 2.13.0

To reproduce the issue:
I created the cluster of 3 nodes on local machine using following commands:
etcd0 node1 script:
/home/vf-root/installed/etcd/etcd --name er-etcd0 \
    --data-dir /var/lib/etcd/er-ms-node0 \
    --listen-client-urls http://0.0.0.0:2379 \
    --advertise-client-urls http://127.0.0.1:2379 \
    --listen-peer-urls http://127.0.0.1:2380 \
    --initial-advertise-peer-urls http://127.0.0.1:2380 \
    --initial-cluster er-etcd0=http://127.0.0.1:2380,er-etcd1=http://127.0.0.1:2381,er-etcd2=http://127.0.0.1:2382 \
    --initial-cluster-token er-etcd-cluster \
    --initial-cluster-state new

etcd1 node2 script:
#Before running this script, please run command sudo rm -rf /var/lib/etcd

/home/vf-root/installed/etcd/etcd --name er-etcd1 \
    --data-dir /var/lib/etcd/er-ms-node1 \
    --listen-client-urls http://0.0.0.0:2378 \
    --advertise-client-urls http://127.0.0.1:2378 \
    --listen-peer-urls http://127.0.0.1:2381 \
    --initial-advertise-peer-urls http://127.0.0.1:2381 \
    --initial-cluster er-etcd0=http://127.0.0.1:2380,er-etcd1=http://127.0.0.1:2381,er-etcd2=http://127.0.0.1:2382 \
    --initial-cluster-token er-etcd-cluster \
    --initial-cluster-state new

etcd2 node3 script:
/home/vf-root/installed/etcd/etcd --name er-etcd2 \
    --data-dir /var/lib/etcd/er-ms-node2 \
    --listen-client-urls http://0.0.0.0:2377 \
    --advertise-client-urls http://127.0.0.1:2377 \
    --listen-peer-urls http://127.0.0.1:2382 \
    --initial-advertise-peer-urls http://127.0.0.1:2382 \
    --initial-cluster er-etcd0=http://127.0.0.1:2380,er-etcd1=http://127.0.0.1:2381,er-etcd2=http://127.0.0.1:2382 \
    --initial-cluster-token er-etcd-cluster \
    --initial-cluster-state new

While you run above 3 scripts it would create the 3 node etcd-cluster, It is working with 3 node and 2 node etcd cluster:

Issue can be reproduce while doing this step:
1.Required to down 2 etcd node from running etcd-cluster.
2.Uset etcd4j library to persist key value pair, it would not able to find single node running etcd cluster and gives the error.

Let me know if you required more things to do.

**Comment by lburgazzoli** [comment]
A few questions:
- what is the purpose of "sudo rm -rf /var/lib/etcd" ? Doesn't that remove the data dir of node 1
- when you stop the two nodes, is etcd already connected or you run it after the nodes have been stopped ?

**Comment by suresh-chaudhari** [comment]
- what is the purpose of "sudo rm -rf /var/lib/etcd" ? Doesn't that remove the data dir of node 1
  This is just defined for who want to create new cluster. forget this steps it doesn't create problem anywhere and I am not using this command

when you stop the two nodes, is etcd already connected or you run it after the nodes have been stopped ?
I am running the test programme again while while disconnect the two nodes.

**Comment by lburgazzoli** [comment]
To recap:

1. create a 3 node cluster
2. start an etcd4j test --> works
3. stop 2 nodes
4. start an etcd4j test --> fail

Correct ? 
Can you tell me how do you create the etcd4j client ?

**Comment by suresh-chaudhari** [comment]
Yes it exactly happens whatever you defined.

This is the whatever exactly I am using this etcd client sample:

        try (EtcdClient etcd = new EtcdClient("admin","vodafone@123",firstUri/*, secondUri, thirdUri*/)) {
            System.out.println(etcd.getVersion());
            EtcdKeysResponse response = etcd.put("foo", "bar").send().get();
            // Prints out: bar
            System.out.println(response.node.value);
        }

**Comment by suresh-chaudhari** [comment]
This is the log just recently I got in running server with while down 2 node.

This may help you.

Caused by: mousio.etcd4j.responses.EtcdException: [300]: Raft Internal Error, cause: etcdserver: request timed out, at index: 0
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:224) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:401) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:65) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789) ~[jackson-databind-2.8.3.jar:2.8.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2964) ~[jackson-databind-2.8.3.jar:2.8.3]
        at mousio.etcd4j.responses.EtcdResponseDecoders$JsonDecoder.decode(EtcdResponseDecoders.java:56) ~[etcd4j-2.13.0.jar:2.13.0]
        at mousio.etcd4j.transport.EtcdResponseHandler.channelRead0(EtcdResponseHandler.java:129) ~[etcd4j-2.13.0.jar:2.13.0]
        at mousio.etcd4j.transport.EtcdResponseHandler.channelRead0(EtcdResponseHandler.java:47) ~[etcd4j-2.13.0.jar:2.13.0]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) ~[netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-common-4.1.7.Final.jar:4.1.7.Final]
        ... 1 common frames omitted

**Comment by lburgazzoli** [comment]
What I can see is that there is an exception thrown by etcd:

```
[300]: Raft Internal Error, cause: etcdserver: request timed out, at index: 0
```

Does that works with curl  ?

**Comment by suresh-chaudhari** [comment]
While making with curl directly to etcd server it is working actually. I guess issue is in this client.

**Comment by suresh-chaudhari** [comment]
Sorry to mention above comment, I just tested with this existing cluster and getting this error
on etcd server while making curl command

{"errorCode":300,"message":"Raft Internal Error","cause":"etcdserver: request timed out","index":0}

**Comment by lburgazzoli** [comment]
So the behavior is the same with etcd4j and curl correct ?

**Comment by suresh-chaudhari** [comment]
It seems like now. do you thing etcd-cluster is not working with single node?

**Comment by lburgazzoli** [comment]
Do you kill the nodes or remove them for the cluster (etcdctl memeber remove id) ? 
If you just kill the node, the cluster may enter in a mis-configured cluster state, if you instead remove the nodes from the cluster it should not fail

**Comment by suresh-chaudhari** [comment]
I am simply running the cluster and downing the node by using ctrl+d command. I don't whether they are killing the node or removing Id.

**But this failover happen anywhere, machine will crash any time then etcd-cluster must require to work.**

can you provide the command to remove nodes from cluster?

**Comment by suresh-chaudhari** [comment]
Hi, 
One question more, if we remove the node from the cluster then why it is working with 2 node cluster.?

**Comment by lburgazzoli** [comment]
You should read the clustering guide, in particular: https://coreos.com/etcd/docs/latest/v2/admin_guide.html#optimal-cluster-size

So a cluster of 3 nodes can handle a failure of 1 node but not 2, if you use  ```etcdctl memeber remove $(id-of-your-node}``` the cluster is aware of what's happening so it can handle the situation.

**Comment by lburgazzoli** [comment]
Going to close this issue, please open it again if you find anything related to etcd4j
